name: Terraform Plan

run-name: Terraform Plan Workflow
on:
  push:
    branches:
      - "*"

jobs:
  terraform:
    name: Run Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: aws/src/terraform
        run: terraform init

      - name: Generate Terraform Plan
        working-directory: aws/src/terraform
        run: terraform plan -var="db_host=terraform-xyz.rds.amazonaws.com" -var="db_user=admin" -var="db_pass=mypassword" -var="db_name=mydb" -out=terraform.plan

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: aws/src/terraform/terraform.plan
          retention-days: 7
